// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.19.6
// source: protos/connections.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Every message sent needs to have action
// so we know which proto messages to use.
// action is 1st frame sent in zmq message
type Actions int32

const (
	Actions_UNKNOWN       Actions = 0
	Actions_ADD_DEALER    Actions = 1
	Actions_REMOVE_DEALER Actions = 2
	Actions_ADD_CLIENT    Actions = 3
	Actions_REMOVE_CLIENT Actions = 4
)

// Enum value maps for Actions.
var (
	Actions_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADD_DEALER",
		2: "REMOVE_DEALER",
		3: "ADD_CLIENT",
		4: "REMOVE_CLIENT",
	}
	Actions_value = map[string]int32{
		"UNKNOWN":       0,
		"ADD_DEALER":    1,
		"REMOVE_DEALER": 2,
		"ADD_CLIENT":    3,
		"REMOVE_CLIENT": 4,
	}
)

func (x Actions) Enum() *Actions {
	p := new(Actions)
	*p = x
	return p
}

func (x Actions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Actions) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_connections_proto_enumTypes[0].Descriptor()
}

func (Actions) Type() protoreflect.EnumType {
	return &file_protos_connections_proto_enumTypes[0]
}

func (x Actions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Actions.Descriptor instead.
func (Actions) EnumDescriptor() ([]byte, []int) {
	return file_protos_connections_proto_rawDescGZIP(), []int{0}
}

type ActionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       Actions                `protobuf:"varint,1,opt,name=actions,proto3,enum=envelope.Actions" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionMsg) Reset() {
	*x = ActionMsg{}
	mi := &file_protos_connections_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMsg) ProtoMessage() {}

func (x *ActionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_connections_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMsg.ProtoReflect.Descriptor instead.
func (*ActionMsg) Descriptor() ([]byte, []int) {
	return file_protos_connections_proto_rawDescGZIP(), []int{0}
}

func (x *ActionMsg) GetActions() Actions {
	if x != nil {
		return x.Actions
	}
	return Actions_UNKNOWN
}

type Service struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DealerId       string                 `protobuf:"bytes,1,opt,name=dealer_id,json=dealerId,proto3" json:"dealer_id,omitempty"`
	RouterHost     string                 `protobuf:"bytes,2,opt,name=router_host,json=routerHost,proto3" json:"router_host,omitempty"`
	RouterPort     int32                  `protobuf:"varint,3,opt,name=router_port,json=routerPort,proto3" json:"router_port,omitempty"`
	RouterEndpoint string                 `protobuf:"bytes,4,opt,name=router_endpoint,json=routerEndpoint,proto3" json:"router_endpoint,omitempty"`
	RouterId       string                 `protobuf:"bytes,5,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_protos_connections_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_protos_connections_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_protos_connections_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetDealerId() string {
	if x != nil {
		return x.DealerId
	}
	return ""
}

func (x *Service) GetRouterHost() string {
	if x != nil {
		return x.RouterHost
	}
	return ""
}

func (x *Service) GetRouterPort() int32 {
	if x != nil {
		return x.RouterPort
	}
	return 0
}

func (x *Service) GetRouterEndpoint() string {
	if x != nil {
		return x.RouterEndpoint
	}
	return ""
}

func (x *Service) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Service) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type BroadcastServices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastServices) Reset() {
	*x = BroadcastServices{}
	mi := &file_protos_connections_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastServices) ProtoMessage() {}

func (x *BroadcastServices) ProtoReflect() protoreflect.Message {
	mi := &file_protos_connections_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastServices.ProtoReflect.Descriptor instead.
func (*BroadcastServices) Descriptor() ([]byte, []int) {
	return file_protos_connections_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastServices) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

// *
// Every message sent must have use Evelope
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcId         string                 `protobuf:"bytes,1,opt,name=src_id,json=srcId,proto3" json:"src_id,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	SrcPort       int32                  `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstId         string                 `protobuf:"bytes,4,opt,name=dst_id,json=dstId,proto3" json:"dst_id,omitempty"`
	Dst           string                 `protobuf:"bytes,5,opt,name=dst,proto3" json:"dst,omitempty"`
	DstPort       int32                  `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Actions       Actions                `protobuf:"varint,7,opt,name=actions,proto3,enum=envelope.Actions" json:"actions,omitempty"`
	MsgId         string                 `protobuf:"bytes,8,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protos_connections_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protos_connections_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protos_connections_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetSrcId() string {
	if x != nil {
		return x.SrcId
	}
	return ""
}

func (x *Envelope) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Envelope) GetSrcPort() int32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Envelope) GetDstId() string {
	if x != nil {
		return x.DstId
	}
	return ""
}

func (x *Envelope) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *Envelope) GetDstPort() int32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Envelope) GetActions() Actions {
	if x != nil {
		return x.Actions
	}
	return Actions_UNKNOWN
}

func (x *Envelope) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Envelope) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

var File_protos_connections_proto protoreflect.FileDescriptor

var file_protos_connections_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x09, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x73, 0x67, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0xe3, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x61, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x33, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x74, 0x41, 0x74, 0x22, 0x42, 0x0a, 0x11, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65,
	0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x8b, 0x02, 0x0a, 0x08, 0x45, 0x6e,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x72, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x72, 0x63, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x72, 0x63, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x2b,
	0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x06, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x2a, 0x5c, 0x0a, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x41, 0x44, 0x44, 0x5f, 0x44, 0x45, 0x41, 0x4c, 0x45, 0x52, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x44, 0x45, 0x41, 0x4c, 0x45, 0x52,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x44, 0x44, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54,
	0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x43, 0x4c, 0x49,
	0x45, 0x4e, 0x54, 0x10, 0x04, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x72, 0x6f, 0x6f, 0x6e, 0x69, 0x61, 0x6d, 0x2f, 0x6d, 0x73, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_connections_proto_rawDescOnce sync.Once
	file_protos_connections_proto_rawDescData []byte
)

func file_protos_connections_proto_rawDescGZIP() []byte {
	file_protos_connections_proto_rawDescOnce.Do(func() {
		file_protos_connections_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_connections_proto_rawDesc), len(file_protos_connections_proto_rawDesc)))
	})
	return file_protos_connections_proto_rawDescData
}

var file_protos_connections_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_connections_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_connections_proto_goTypes = []any{
	(Actions)(0),                  // 0: envelope.Actions
	(*ActionMsg)(nil),             // 1: envelope.ActionMsg
	(*Service)(nil),               // 2: envelope.Service
	(*BroadcastServices)(nil),     // 3: envelope.BroadcastServices
	(*Envelope)(nil),              // 4: envelope.Envelope
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_protos_connections_proto_depIdxs = []int32{
	0, // 0: envelope.ActionMsg.actions:type_name -> envelope.Actions
	5, // 1: envelope.Service.sent_at:type_name -> google.protobuf.Timestamp
	2, // 2: envelope.BroadcastServices.services:type_name -> envelope.Service
	0, // 3: envelope.Envelope.actions:type_name -> envelope.Actions
	5, // 4: envelope.Envelope.sent_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_connections_proto_init() }
func file_protos_connections_proto_init() {
	if File_protos_connections_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_connections_proto_rawDesc), len(file_protos_connections_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_connections_proto_goTypes,
		DependencyIndexes: file_protos_connections_proto_depIdxs,
		EnumInfos:         file_protos_connections_proto_enumTypes,
		MessageInfos:      file_protos_connections_proto_msgTypes,
	}.Build()
	File_protos_connections_proto = out.File
	file_protos_connections_proto_goTypes = nil
	file_protos_connections_proto_depIdxs = nil
}
