package conf

const MSG_DIR_HOST = "MSG_DIR_HOST"
const MSG_DIR_PORT = "MSG_DIR_PORT"

const MSG_DEALER_ID = "MSG_DEALER_ID"
const MSG_DEALER_HOST = "MSG_DEALER_HOST"
const MSG_DEALER_PORT = "MSG_DEALER_PORT"

const MSG_IHTTP_HOST = "MSG_IHTTP_HOST"
const MSG_IHTTP_PORT = "MSG_IHTTP_PORT"
